"""Change columns with any telegram id to str

Revision ID: abdefe9a5f1a
Revises: f4b35635d5bb
Create Date: 2024-09-27 18:51:05.148496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abdefe9a5f1a'
down_revision: Union[str, None] = 'f4b35635d5bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('chats', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('operators', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operators', 'id',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('chats', 'id',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('admins', 'id',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
